branches:
  only:
    - gh-pages
    - /^.*$/
language: ruby
rvm:
- 2.4.0
before_install:
- travis_retry gem install jekyll
- travis_retry gem install json
- travis_retry gem install jekyll-sitemap
script: jekyll build
