title: Redecentralize
url: https://redecentralize.org
timezone: Europe/London
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
collections:
  radar:
    output: true
    permalink: /radar/:title
authors:
  frabcus:
    display_name: Francis Irving
    picname: frabcus.jpg
    link: https://twitter.com/frabcus
  shevski:
    display_name: Irina Bolychevsky
    picname: shevski.jpg
    link: /about/#ira
  rossjones:
    display_name: Ross Jones
    picname: rossjones.jpg
    link: https://twitter.com/rossjones
  mikedeplume:
    display_name: Mike Sandford
    picname: mikedeplume.jpg
    link: https://twitter.com/mikedeplume
  dknestaut:
    display_name: Danny Knestaut
    picname: dknestaut.jpg
    link: https://twitter.com/dknestaut
  pierreo:
    display_name: Pierre Ozoux
    picname: pierreo.jpg
    link: https://twitter.com/pierreozoux
  michielbdejong:
    display_name: Michiel de Jong
    picname: michielbdejong.png
    link: https://twitter.com/michieldejong
  gerben:
    display_name: Gerben
    link: /about/#gerben
