name: Redecentralize
timezone: Europe/London
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass

authors:
  frabcus:
    display_name: Francis Irving
    picname: frabcus.jpg
    link: https://twitter.com/frabcus
  shevski:
    display_name: Irina Bolychevsky
    picname: shevski.jpg
    link: https://twitter.com/shevski
  rossjones:
    display_name: Ross Jones
    picname: rossjones.jpg
    link: https://twitter.com/rossjones
  mikedeplume:
    display_name: Mike Sandford
    picname: mikedeplume.jpg
    link: https://twitter.com/mikedeplume
  dknestaut:
    display_name: Danny Knestaut
    picname: dknestaut.jpg
    link: https://twitter.com/dknestaut
  pierreo:
    display_name: Pierre Ozoux
    picname: pierreo.jpg
    link: https://twitter.com/pierreozoux
  michielbdejong:
    display_name: Michiel de Jong
    picname: michielbdejong.png
    link: https://twitter.com/michieldejong

exclude:
  - "vendor/*.html"
